graphhopper:
  datareader.file: export.osm
  graph.location: graph-cache
  import.osm.ignored_highways: footway,cycleway,path,pedestrian,steps
  graph.encoded_values: car_access, car_average_speed, road_class

  profiles:
    - name: ambulance_routine
      custom_model:
        distance_influence: 15
        speed:
          - if: "true"
            limit_to: "car_average_speed"

    - name: ambulance_emergency
      custom_model:
        distance_influence: 0
        priority:
          - if: "road_class == RESIDENTIAL"
            multiply_by: 0.8
        speed:
          - if: "true"
            limit_to: "car_average_speed"
          - if: "true"
            multiply_by: 1.3